### ISSUE TITLE
xpack build broken

### ISSUE THREAD

**Issue by mklomp** [koendv/stm32duino-raspberrypi#2]
The file [referenced to download xpack](https://github.com/koendv/stm32duino-raspberrypi/blob/e23fe40960c776ed5fab8ba9b43a5acecdad34a3/BoardManagerFiles/package_stm_index.json#L1260) does not exists anymore. The new[ 9.3.1 version](https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/tag/v9.3.1-1.1) does support ARM.

**Comment by jarekdudzinski** [comment]
@mklomp Hey. I've forked this and fixed it - created pull request, in the meantime you can use mine branch:
https://raw.githubusercontent.com/jarekdudzinski/stm32duino-raspberrypi/master/BoardManagerFiles/package_stm_index.json

**Comment by jarekdudzinski** [comment]
PS: tools installation path changed:
~/.arduino15/packages/STM32/tools/STM32Tools/1.4.0/tools/linux/

**Comment by koendv** [comment]
FIxed. 

STM has said the [next stm32duino release will have support for arm hosts](https://github.com/stm32duino/Arduino_Core_STM32/issues/1111#issuecomment-654649988); we'll see.

**Comment by mklomp** [comment]
After I saw xpack released an ARM-version, I already hoped for a ARM version of stm32duino in the next release.

**Comment by koendv** [comment]
Now you have on raspbarry an unofficial stm32duino, and an unofficial [visual studio code](https://code.headmelted.com/). 
I expect we'll have an official stm32duino, and an official eclipse later this year.
