### ISSUE TITLE
Cannot install: Error downloading xpack-arm-...

### ISSUE THREAD

**Issue by jarekdudzinski** [koendv/stm32duino-raspberrypi#3]
Cannot install: Error downloading ... xpack-arm-none-eabi-gcc-9.2.1-1.2-linux-arm.tar.gz

**Comment by jarekdudzinski** [comment]
@koendv Created "pull-request" with fix... At least I think so - it's first time I'm really using github or ... fixing such things :D
But it worked on my Ras Pi 4 - using my fork - so I think I didn't messed anything up :D

**Comment by koendv** [comment]
OK. Question: Why did you remove the "allow_insecure_packages=true" in preferences?

**Comment by jarekdudzinski** [comment]
Not sure - probably by mistake :)
