### ISSUE TITLE
Generic STM32F4 series is not working on Raspberry pi via STM32CubeProgrammer(Serial)

### ISSUE THREAD

**Issue by darlovic** [koendv/stm32duino-raspberrypi#8]
Generic STM32F4 series is not working on Raspberry pi via STM32CubeProgrammer(Serial) in Arduino IDE while uploading the sketch to the controller the whole code has been Erasing instead on running in the microcontroller. Thanks in advance for any support.

**Comment by koendv** [comment]
Sorry, can't help.
